config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'work/:id' => 'public#show', as: :work
  get 'work_process/:id' => 'public#show_process', as: :work_process
  get 'about' => 'public#about'
  get 'contact' => 'public#contact'
  get 'awards' => 'public#awards'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'admin' => 'works#statistics'

  get 'edit_about' => 'about_paragraphs#edit'
  patch 'update_about' => 'about_paragraphs#update'

  resources :works do
    
    member do
      get :delete
      get :show_process
      patch :update_position
    end

    resources :pictures do
      member do
        get :delete
      end
    end

    resources :process_pictures do
      member do
        get :delete
      end
    end

  end

  get 'manage_awards' => 'works#manage_awards'
  

end

app/models/work.rb
class Work < ActiveRecord::Base
  before_validation :pre_process

  has_many :pictures, dependent: :destroy
  has_many :process_pictures, dependent: :destroy
  acts_as_list scope: [:award]

  has_attached_file :thumbnail, :styles => { :thumb => "200x200>", large: "800x800>" }
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true,
                   uniqueness: true
  validates :thumbnail, presence: true

  scope :visible, lambda { where(visible: true) }
  scope :normal, lambda { where(award: false) }
  scope :awarded, lambda { where(award: true) }
  scope :sorted, lambda { order('position') }

  def pre_process
    self.name = name.titleize
    unless visible
      self.move_to_bottom
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_work, except: [:new, :create, :index, :statistics, :migrate_hit_counts, :manage_awards]

  def statistics
    get_hit_counts
    @works = Work.normal.sort_by do |work|
      - @work_hits[work.id]
    end
  end

  # migrate from old "work_xxx" category to new "xxx"
  def migrate_hit_counts
    all_hits = HitCount.all
    all_hits.each do |hit|
      if hit.cat.start_with? "work_"
        puts "Migrate: Category: \"#{hit.cat}\" is in old format!"
        new_cat = hit.cat.delete "work_"
        new_hit = HitCount.find_by_cat(new_cat)
        # if there is alread new category records
        if new_hit
          puts "Migrate: Category: \"#{new_cat}\" already exists, update it"
          # add old hits to new
          new_hit.hits += hit.hits
          puts "Migrate: Add #{hit.hits} hits to Category: \"#{new_cat}\""
          if new_hit.save
            puts "Migrate: Update Category: \"#{new_cat}\" success!"
            hit.destroy
            puts "Migrate: Category: \"#{hit.cat}\" destroyed"
          end
        # if there is no new category yet
        else
          puts "Migrate: rename old record"
          # rename category 
          hit.cat =  new_cat
          if hit.save
            puts "Migrate: rename success!"
          end
        end
      else
        puts "Migrate: Category: \"#{hit.cat}\" looks OK, nothing to do with it"
      end
    end
    redirect_to action: :statistics
  end

  def new
    @work = Work.new
    @work_count = Work.normal.count + 1
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      flash[:success] = "New Work #{@work.name} created!"
      create_pictures
      redirect_to edit_work_path(@work.id)
    else
      flash[:error] = "Create new work failed!"
      @work_count = Work.normal.count + 1
      render 'new'
    end
  end

  def index
    @works = Work.normal.sorted
    @work_count = Work.normal.count
  end

  def manage_awards
    @works = Work.awarded.sorted
    @work_count = Work.awarded.count
  end

  def show
    @pictures = @work.pictures.sorted
    @process_picture_count = @work.process_pictures.count
  end

  def show_process
    @pictures = @process_pictures
    render 'show'
  end

  def edit
  end

  def update
    if @work.update_attributes(work_params)
      flash[:success] = "Work: #{@work.name} updated!"
      create_pictures
      redirect_to action: :show
    else
      flash[:error] = "Work: #{@work.name} update failed!"
      render 'edit'
    end
  end

  def update_position
    if @work.update_attributes(work_params)
      if @work.award
        flash[:success] = "Award: #{@work.name} updated!"
        redirect_to action: :manage_awards
      else
        flash[:success] = "Work: #{@work.name} updated!"
        redirect_to action: :index
      end
    else
      if @work.award
        flash[:error] = "Award: #{@work.name} update failed!"
        redirect_to action: :manage_awards
      else
        flash[:error] = "Work: #{@work.name} update failed!"
        redirect_to action: :index
      end
    end
  end
  
  def delete
  end

  def destroy
    @work.destroy
    if @work.award
      flash[:alert] = "Award: #{@work.name} deleted!"
      redirect_to action: :manage_awards
    else
      flash[:alert] = "Work: #{@work.name} deleted!"
      redirect_to action: :index
    end
  end


  private
    def work_params
      params.require(:work).permit(:name, :thumbnail, :position, :visible, :description, :award)
    end

    def create_pictures
      if params[:pictures]
        params[:pictures].each do |picture| 
          @work.pictures.create(file: picture)
        end
      end

      if params[:process_pictures]
        params[:process_pictures].each do |picture| 
          @work.process_pictures.create(file: picture)
        end
      end
    end

    def find_work
      @work = Work.find params[:id]
      @work_count = Work.normal.count
      @pictures = @work.pictures.sorted
      @process_pictures = @work.process_pictures.sorted
    end

    def get_hit_counts
      @overall_hits = HitCount.find_by_cat('all').hits
      @unique_visitors = HitCount.find_by_cat('unique').hits
      @work_hits = Hash.new(0)
      @page_hits = {}
      @total_work_hits = 0
      HitCount.all.each do |hit|
        if hit.cat =~ /\d+/
          @work_hits[hit.cat.to_i] = hit.hits.to_i
          @total_work_hits += hit.hits.to_i
        else
          unless hit.cat == 'all' || hit.cat == 'unique'
            @page_hits[hit.cat] = hit.hits.to_i
          end
        end
      end
    end
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/works/_form.html.erb
<%= error_messages_for(@work) %>
<div class='form-group'>
  <%= f.label :name, class: 'control-label col-md-3' %>
  <div class='col-md-9'>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
</div>

<div class='form-group'>
  <%= f.label :position, class: 'control-label col-md-3' %>
  <div class=' col-md-3'>
    <%= f.select :position, 1..@work_count, {}, class: 'form-control' %>
  </div>
</div>

<div class='form-group'>
  <div class='col-md-9 col-md-offset-3'>
    <div class='checkbox text-left'>
      <label>
        <%= f.check_box :visible %> Visible
      </label>
    </div>
  </div>
</div>

<div class='form-group'>
  <div class='col-md-9 col-md-offset-3'>
    <div class='checkbox text-left'>
      <label>
        <%= f.check_box :award %> Awarded
      </label>
    </div>
  </div>
</div>

<div class='form-group'>
  <%= f.label :description, class: 'control-label col-md-3' %>
  <div class='col-md-9'>
    <%= f.text_area :description, size: '40x5', class: 'form-control'  %>
  </div>
</div>

<div class='form-group'>
  <%= f.label :thumbnail, class: 'control-label col-md-3' %>
  <div class='col-md-9'>
    <%= f.file_field :thumbnail, class: 'form-control'  %>
  </div>
</div>

<div class='form-group'>
  <%= label_tag 'pictures_', 'Finished Pictures', class: 'control-label col-md-3' %>
  <div class='col-md-9'>
    <%= file_field_tag "pictures[]", type: :file, multiple: true, class: 'form-control'  %>
  </div>
</div>

<div class='form-group'>
  <%= label_tag 'process_pictures_', 'Process Pictures', class: 'control-label col-md-3' %>
  <div class='col-md-9'>
    <%= file_field_tag "process_pictures[]", type: :file, multiple: true, class: 'form-control'  %>
  </div>
</div>
<div class='form-group'>
  <div class='col-md-3 col-md-offset-3'>
    <%= f.submit class: 'form-control btn btn-primary' %>
  </div>
</div>

app/views/works/delete.html.erb
<% @title = "Delete Work!" %>
<div class='col-md-4 col-md-offset-4 well'>
  <h4 class='form-title'>Delete "<%= @work.name %>"?</h4> 

  <div class='form-group'>
    <%= image_tag @work.thumbnail.url(:thumb), alt: "#{@work.name}" %>
  </div>
  <%= form_for @work, :url => {action: :destroy}, method: 'delete', html: {class: 'form delete-work'} do |f| %>
    <div class='form-group'>
      <%= link_to 'Cancel', {action: (@work.award ? :manage_awards : :index)}, class: 'btn btn-success' %>
      <%= f.submit 'Delete', class: 'btn btn-danger'%>
    </div>
  <% end %>
</div>

app/views/works/edit.html.erb
<% @title = "Edit \"#{@work.name}\"" %>
<h4 class='form-title'>Edit "<%= @work.name %>"</h4>

<div class='row well'>
  <div class='col-md-3'>
    <%= link_to image_tag(@work.thumbnail.url(:thumb), alt: @work.name), {action: :show} %>
  </div>

  <div class='col-md-9'>
    <%= form_for @work, :url => {action: :update}, :html => { :multipart => true, class: 'form-horizontal'} do |f| %>
      <%= render partial: 'form', locals: {f: f} %>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col-md-5 well'>
    <div class='form-group'>
      <%= link_to 'manage pictures', work_pictures_path(@work), class: 'btn btn-info' %>
    </div>

    <% @pictures.each do |p| %>
      <div class='form-group'><%= image_tag p.file.url(:thumb), alt: 'Picture' %></div>
    <% end %>
  </div>

  <div class='col-md-5 col-md-offset-1 well'>
    <div class='form-group'>
      <%= link_to 'Manage Process Pictures', work_process_pictures_path(@work), class: 'btn btn-info' %>
    </div>

    <% @process_pictures.each do |p| %>
      <div class='form-group'><%= image_tag p.file.url(:thumb), alt: 'Picture' %></div>
    <% end %>
  </div>
</div>

app/views/works/index.html.erb
<% @title = 'Manage Works' %>
<% @works.each do |work| %>
  <div class='well'>
    <div class='row'>
      <h4 class='form-title'><%= work.name %></h4>
      <div class='col-md-2'>
        <%= link_to image_tag(work.thumbnail.url(:thumb), alt: work.name), {action: :show, id: work.id}  %>
      </div>

      <div class='col-md-10'>
        <%= form_for work, url: update_position_work_path(work), html: {class: 'form-horizontal'} do |f| %>

          <div class='form-group'>
            <%= f.label :position, for: "work_position_#{work.id}", class: 'control-label col-md-3' %>
            <div class='col-md-9'><%= f.select :position, 1..@work_count, {}, class: 'form-control', id: "work_position_#{work.id}"  %></div>
          </div>

          <div class='form-group'>
            <div class='col-md-9 col-md-offset-3'>
              <div class='checkbox text-left'>
                <label>
                  <%= f.check_box :visible, {id: "work_visible_#{work.id}"}  %>Visible
                </label> 
              </div>
            </div>
          </div>

          <div class='form-group'>
            <div class='col-md-9 col-md-offset-3'>
              <%= f.submit 'Update Position and Visibility', class: 'form-control btn btn-success' %>
            </div>
          </div>


          <div class='form-group'>
            <div class='col-md-4 col-md-offset-3'>
              <%= link_to "Edit", edit_work_path(work), class: 'form-control btn btn-primary' %>
            </div>

            <div class='col-md-4 col-md-offset-1'>
              <%= link_to "Delete", delete_work_path(work), class: 'form-control btn btn-danger' %>
            </div>
          </div>

          <div class='form-group'>
            <div class='col-md-4 col-md-offset-3'>
              <%= link_to 'Manage Pictures', work_pictures_path(work), class: 'form-control btn btn-info' %>
            </div>
            <div class='col-md-4 col-md-offset-1'>
              <%= link_to 'Manage Process Pictures', work_process_pictures_path(work), class: 'form-control btn btn-info' %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/works/manage_awards.html.erb
<% @title = 'Manage Awards' %>
<% @works.each do |work| %>
  <div class='well'>
    <div class='row'>
      <h4 class='form-title'><%= work.name %></h4>
      <div class='col-md-2'>
        <%= link_to image_tag(work.thumbnail.url(:thumb), alt: work.name), {action: :show, id: work.id}  %>
      </div>

      <div class='col-md-10'>
        <%= form_for work, url: update_position_work_path(work), html: {class: 'form-horizontal'} do |f| %>

          <div class='form-group'>
            <%= f.label :position, for: "work_position_#{work.id}", class: 'control-label col-md-3' %>
            <div class='col-md-9'><%= f.select :position, 1..@work_count, {}, class: 'form-control', id: "work_position_#{work.id}"  %></div>
          </div>

          <div class='form-group'>
            <div class='col-md-9 col-md-offset-3'>
              <div class='checkbox text-left'>
                <label>
                  <%= f.check_box :visible, {id: "work_visible_#{work.id}"}  %>Visible
                </label> 
              </div>
            </div>
          </div>

          <div class='form-group'>
            <div class='col-md-9 col-md-offset-3'>
              <%= f.submit 'Update Position and Visibility', class: 'form-control btn btn-success' %>
            </div>
          </div>


          <div class='form-group'>
            <div class='col-md-4 col-md-offset-3'>
              <%= link_to "Edit", edit_work_path(work), class: 'form-control btn btn-primary' %>
            </div>

            <div class='col-md-4 col-md-offset-1'>
              <%= link_to "Delete", delete_work_path(work), class: 'form-control btn btn-danger' %>
            </div>
          </div>

          <div class='form-group'>
            <div class='col-md-4 col-md-offset-3'>
              <%= link_to 'Manage Pictures', work_pictures_path(work), class: 'form-control btn btn-info' %>
            </div>
            <div class='col-md-4 col-md-offset-1'>
              <%= link_to 'Manage Process Pictures', work_process_pictures_path(work), class: 'form-control btn btn-info' %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/works/new.html.erb
<% @title = 'Create a New Work/Award' %>
<div class='well'>
  <h4 class='form-title'>New Work/Award</h4>
  <%= form_for( @work, :url => {action: :create}, :html => { :multipart => true, class: 'form-horizontal' }) do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
  <% end %>
</div>

app/views/works/show.html.erb
<% @title = @work.name %>
<div class="well">
  <div class='work-header'>
    <h4 id='work-name'><%= @work.name %></h4>
    <p id="work-description"><%= @work.description %></p>
    <div class=""><%= link_to 'Edit this work', edit_work_path, class: 'btn btn-primary' %></div>
  </div>
</div>

<div class='well'>
  <div class='row links'>
    <div class='col-xs-4 pull-right'>
      <%= render partial: 'process_links' %>
    </div>
  </div>

  <div id='pictures' class='row'>
    <% @pictures.each do |p| %>
      <%= image_tag p.file.url(:large), class: 'work-image', alt: "#{@work.name} ##{p.position} by Moyu Zhang" %>
    <% end %>
  </div>

  <div class='row links'>
    <div class='col-xs-4 pull-right'>
      <%= render partial: 'process_links' %>
    </div>
  </div>
</div>

app/views/works/statistics.html.erb
<% @title = 'Work Statistics' %>
<div class="well">
  <div class='row'>
    <h5 class='col-md-6 text-right'>Overall page visits :</h5>
    <h5 class='col-md-6 text-left'><%= @overall_hits %></h5>
  </div>

  <div class='row'>
    <h5 class='col-md-6 text-right'>Unique visitors :</h5>
    <h5 class='col-md-6 text-left'><%= @unique_visitors %></h5>
  </div>

  <div class='row'>
    <h5 class='col-md-6 text-right'>Work pages visits :</h5>
    <h5 class='col-md-6 text-left'><%= @total_work_hits %></h5>
  </div>

  <% @page_hits.each do |page, hits| %>
    <div class='row'>
      <h5 class='col-md-6 text-right'>"<%= page.titleize %>" page visits :</h5>
      <h5 class='col-md-6 text-left'><%= hits %></h5>
    </div>
  <% end %>
</div>
<% @works.each do |work| %>
  <div class='well'>
    <div class='row'>
      <div class='col-md-2'>
        <%= link_to image_tag(work.thumbnail.url(:thumb), alt: work.name), {action: :show, id: work.id}  %>
      </div>

      <div class='col-md-10'>
        <div class='row'>
          <h5 class='form-title'><%= work.name %></h5>
        </div>
        <div class='row'>
          <h6 class='col-md-6 text-right'>Created At :</h6>
          <h6 class='col-md-6 text-left'><%= work.created_at.strftime("%Y-%m-%d %H:%M:%S") %></h6>
        </div>
        <div class='row'>
          <h6 class='col-md-6 text-right'>Updated At :</h6>
          <h6 class='col-md-6 text-left'><%= work.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></h6>
        </div>
        <div class='row'>
          <h6 class='col-md-6 text-right'>Visits :</h6>
          <h6 class='col-md-6 text-left'><%= @work_hits[work.id] %></h6>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%#<div class="well">%>
  <%# link_to 'Migrate Old Records', migrate_hit_counts_works_path, class: 'btn btn-default' %>
<%#</div>%>