config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'work/:id' => 'public#show', as: :work
  get 'work_process/:id' => 'public#show_process', as: :work_process
  get 'about' => 'public#about'
  get 'contact' => 'public#contact'
  get 'awards' => 'public#awards'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'admin' => 'works#statistics'

  get 'edit_about' => 'about_paragraphs#edit'
  patch 'update_about' => 'about_paragraphs#update'

  resources :works do
    
    member do
      get :delete
      get :show_process
      patch :update_position
    end

    resources :pictures do
      member do
        get :delete
      end
    end

    resources :process_pictures do
      member do
        get :delete
      end
    end

  end

  get 'manage_awards' => 'works#manage_awards'
  

end

app/models/process_picture.rb
class ProcessPicture < ActiveRecord::Base
  belongs_to :work
  acts_as_list scope: :work

  has_attached_file :file, :styles => { large: "800x", thumb: "200x" }
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  validates :file, presence: true
  validates :work_id, presence: true

  scope :sorted, lambda { order('position') }
end

app/controllers/process_pictures_controller.rb
class ProcessPicturesController < ApplicationController
  layout 'admin'
  
  before_action :confirm_logged_in
  before_action :find_work
  before_action :find_process_picture, except: [:create, :index]

  def create
    if params[:files]
      params[:files].each do |picture|
        @work.process_pictures.create file: picture
      end
      flash[:success] = "#{params[:files].count} Pictures added!"
    end

    redirect_to work_process_pictures_path params[:work_id]
  end

  def index
    @picture = @work.process_pictures.build
    @pictures = @work.process_pictures.sorted
    @picture_count = @pictures.count + 1
  end

  def update
    if @picture.update_attributes(picture_params)
      flash[:success] = "Picture updated!"
      redirect_to work_process_pictures_path params[:work_id]
    else
      flash[:error] = "Update picture failed!"
      redirect_to work_process_pictures_path params[:work_id]
    end
  end

  def delete
    render 'pictures/delete'
  end

  def destroy
    flash[:alert] = "Picture #{@picture.file_file_name} deleted!"
    @picture.destroy
    redirect_to work_process_pictures_path params[:work_id]
  end

  private
    def picture_params
      params.require(:process_picture).permit(:id, :file, :position)
    end

    def find_work
      @work = Work.find(params[:work_id])
    end

    def find_process_picture
      @picture = ProcessPicture.find params[:id]
    end
end

app/views/process_pictures/index.html.erb
<% @title = "Process Pictures for #{@work.name}" %>
<div class="well">
  <div class='work-header'>
    <h4 id='work-name'><%= @work.name %></h4>
    <p id="work-description"><%= @work.description %></p>
    <div class=""><%= link_to 'Edit this work', edit_work_path(@work), class: 'btn btn-primary' %>
    <%= link_to "Manage Finished Pictures", {controller: :pictures}, class: 'btn btn-info' %>
    </div>
  </div>
</div>

<div class='well'>
  <div class='form-group'>
    <h3>Process Pictures</h3>
  </div>
  <%= form_for @picture, url: {action: :create}, html: {multipart: true, class: 'form-horizontal'} do |f| %>
    <div class='form-group'>
      <%= label_tag 'new-files', 'Choose Pictures to upload', class: 'control-label col-md-3' %>
      <div class='col-md-9'><%= file_field_tag "files[]", type: :file, multiple: true, id: 'new-files', class: 'form-control' %></div>
    </div>

    <div class='form-group'>
      <div class='col-md-9 col-md-offset-3'><%= submit_tag 'Upload Pictures', class: 'btn btn-primary form-control' %></div>
    </div>
  <% end %>
</div>

<% @pictures.each do |picture| %>
  <div class='well'>
    <div class='row'>
      <div class='col-md-4'>
        <h4><%= picture.file_file_name %></h4>
        <%= image_tag picture.file.url(:thumb), alt: 'Picture' %>
      </div> 

      <div class='col-md-8'>
        <div class='row'>
          <%= form_for picture, url: {action: :update, id: picture.id}, html: {multipart: true, class: 'form-horizontal'} do |f| %>
            <%= render partial: 'pictures/form', locals: {f: f} %>
            <div class='form-group'>
              <div class='col-md-5 col-md-offset-2'>
                <%= link_to "Delete", delete_work_process_picture_path(id: picture.id), class: 'form-control btn btn-danger ' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>