config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'work/:id' => 'public#show', as: :work
  get 'work_process/:id' => 'public#show_process', as: :work_process
  get 'about' => 'public#about'
  get 'contact' => 'public#contact'
  get 'awards' => 'public#awards'

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'admin' => 'works#statistics'

  get 'edit_about' => 'about_paragraphs#edit'
  patch 'update_about' => 'about_paragraphs#update'

  resources :works do
    
    member do
      get :delete
      get :show_process
      patch :update_position
    end

    resources :pictures do
      member do
        get :delete
      end
    end

    resources :process_pictures do
      member do
        get :delete
      end
    end

  end

  get 'manage_awards' => 'works#manage_awards'
  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <% if @title %>
      <title><%= @title %> | moyuzhang.com</title>
    <% else %>
      <title>Management on moyuzhang.com</title>
    <% end %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-default">
      <div class="container">
        <%= link_to 'Home Page', root_path, class: 'navbar-brand' %>
        <ul class='navbar-nav nav navbar-right'>
          <li><%= link_to 'Statistics', admin_path, class: 'navbar-link' %></li>
          <li><%= link_to 'Manage Works', works_path, class: 'navbar-link' %></li>
          <li><%= link_to 'Manage Awards', manage_awards_path, class: 'navbar-link' %></li>
          <li><%= link_to 'Add New Work/Award', new_work_path, class: 'navbar-link'   %></li>
          <li><%= link_to 'Edit About', edit_about_path, class: 'navbar-link'   %></li>
          <% if session[:user_id] %>
            <li><%= link_to 'Log Out', access_logout_path, class: 'navbar-link'  %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type.to_sym) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @title %>
    <title>moyuzhang.com: <%= @title %></title>
  <% else %>
    <title>Welcome to moyuzhang.com</title>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
</head>
<body>
<% ####################### %>
<div class="header_img">
    <a href="/">
      <%= image_tag "moyuzhang_seal.png", alt: "moyuzhang.com", id: "seal" %>
    </a>
    <a href="/">
      <%= image_tag "moyuzhangblack.png", alt: "moyuzhang.com" %>
    </a>
</div>
<div class="navigator">
    <div class="navigator_row">
        <div class="navigator_cell"><%= link_to image_tag("about.png", alt: "about"), "#" %></a></div>
        <div class="navigator_cell"><%= link_to image_tag("work.png", alt: "work"), works_path %></a></div>
        <div class="navigator_cell"><%= link_to image_tag("contact.png", alt: "contact"), "#" %></a></div>
    </div>
</div>

<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% ####################### %>


<%= yield %>

<% ####################### %>
<div class="content" id="copyright">
<%= image_tag "copyright.png", alt: "copyright" %>
</div>
<% ####################### %>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <% if @title %>
      <title><%= @title %> | moyuzhang.com</title>
    <% else %>
      <title>Welcome to moyuzhang.com</title>
    <% end %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="<%= @og_title %>">
    <meta property="og:type" content="<%= @og_type %>">
    <meta property="og:url" content="<%= @og_url %>">
    <meta property="og:image" content="<%= @og_image %>">
    <meta property="og:site_name" content="<%= @og_site_name %>">
    <meta property="og:description" content="<%= @og_description %>">
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
  </head>
  <body>
    <div class='js-apis'>
      <%# Facebook JavaScript SDK begin %>
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
      <%# Facebook JavaScript SDK end %>
      <%# Pinterest buttons start %>
      <!-- Please call pinit.js only once per page -->
      <script type="text/javascript" async defer  data-pin-color="red" data-pin-height="28" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
      <%# Pinterest buttons end %>
    </div>

    <div class='container'>
      <div class="header_images">
        <%= link_to image_tag("moyuzhang_seal.png", alt: "moyuzhang.com", id: "seal"), :root %>
        <%= link_to "Moyu Zhang", :root, id: "logo" %>
      </div>
      <ul class="navigator list-inline" id="navigator">
        <li><%= link_to "Work", :root, class: "navigation nav-link" %></li>
        <li><%= link_to "Awards", awards_path, class: "navigation nav-link"%></li>
        <li><%= link_to "About", about_path, class: "navigation nav-link" %></li>
        <li><%= link_to "Contact", contact_path, class: "navigation nav-link"%></li>
      </ul>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">

      <div class="container" id="copyright">
        <p class='text-muted'>Design &amp; copyright&copy; Moyu Zhang 2019. Photos by Moyu Zhang, unless otherwise specified.</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/works.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @title %>
    <title>moyuzhang.com | <%= @title %></title>
  <% else %>
    <title>Management on moyuzhang.com</title>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
</head>
<body>

<div class="navigator">
    <div class="navigator_row">
        <div class="navigator_cell"><%= link_to 'Home Page', root_path %></div>
        <div class="navigator_cell"><%= link_to 'Manage Works', works_path %></div>
        <div class="navigator_cell"><%= link_to 'Add New Work', new_work_path %></div>
        <div class="navigator_cell"><%= link_to 'Login', access_login_path %></div>
        <div class="navigator_cell"><%= link_to 'Log Out', access_logout_path %></div>
    </div>
</div>

<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>